import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner"

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { getSession } from "@/lib/auth/auth-server";
import { ProfileSetupModal } from "@/components/ProfileSetupModal";
import { db } from "@/lib/db/db";
import { user, RoleId } from "@/lib/db/auth-schema";
import { eq } from "drizzle-orm";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const dbUser = session?.user?.id
    ? await db.query.user.findFirst({
        where: eq(user.id, session.user.id),
        columns: {
          roleId: true,
        },
      })
    : null;

  return (
    <html lang="en" className={`${geistMono.className} h-full`} suppressHydrationWarning>
      <body className="h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen flex-col">
            <div className="shrink-0">
              <Header userRoleId={dbUser?.roleId as RoleId ?? null} />
            </div>
            <main className="flex flex-1 flex-col">
              {children}
            </main>
            <div className="shrink-0">
              <Footer />
            </div>
          </div>
          <Toaster />
          {session?.user && <ProfileSetupModal user={session.user} />}
        </ThemeProvider>
      </body>
    </html>
  );
}
